"""Environment names for remote credential hydration."""

from __future__ import annotations

# Fleet/gateway org key (distinct from billing's OPENSRE_ORGANIZATION_ID).
FLEET_ORGANIZATION_ID_ENV = "ORGANIZATION_ID"
CREDENTIALS_API_URL_ENV = "OPENSRE_CREDENTIALS_API_URL"
CREDENTIALS_BOOTSTRAP_SECRET_ARN_ENV = "OPENSRE_CREDENTIALS_BOOTSTRAP_SECRET_ARN"
INTEGRATIONS_SECRET_ARN_ENV = "OPENSRE_INTEGRATIONS_SECRET_ARN"
INTEGRATIONS_STORE_PATH_ENV = "OPENSRE_INTEGRATIONS_STORE_PATH"
DEFAULT_EPHEMERAL_INTEGRATIONS_STORE_PATH = "/run/opensre/integrations.json"

__all__ = [
    "CREDENTIALS_API_URL_ENV",
    "CREDENTIALS_BOOTSTRAP_SECRET_ARN_ENV",
    "DEFAULT_EPHEMERAL_INTEGRATIONS_STORE_PATH",
    "FLEET_ORGANIZATION_ID_ENV",
    "INTEGRATIONS_SECRET_ARN_ENV",
    "INTEGRATIONS_STORE_PATH_ENV",
]
